databases:
  - name: ecomerce
    databaseName: ecomercedb_r6ez
    user: admin
services:
  - type: web
    name: mysite
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn projeto_ecomerce.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: projeto_ecomerce
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4