# Generated by Django 4.2.7 on 2024-01-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='data_create',
            field=models.DateField(auto_created=True, auto_now_add=True),
        ),
    ]
