# Generated by Django 4.2.7 on 2024-01-14 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_enderecos_rename_endereço_users_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enderecos',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
