# Generated by Django 4.2.7 on 2024-01-14 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_enderecos_id_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enderecos',
            old_name='id_user',
            new_name='user_id',
        ),
    ]
