# Generated by Django 4.2.7 on 2024-01-14 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_id_user_enderecos_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enderecos',
            old_name='user_id',
            new_name='user',
        ),
    ]
