# Generated by Django 4.2.7 on 2024-01-15 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_user_id_enderecos_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='nasc',
        ),
    ]
