# Generated by Django 4.2.7 on 2024-01-20 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_produtos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enderecos',
            name='bairro',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enderecos',
            name='cidade',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enderecos',
            name='numero',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='enderecos',
            name='rua',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
