# Generated by Django 4.2.7 on 2024-01-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_enderecos_bairro_alter_enderecos_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='nasc',
            field=models.DateField(blank=True, null=True),
        ),
    ]
