# Generated by Django 4.2.7 on 2024-01-24 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_users_nasc'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='google_id',
            field=models.BigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='user_google',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
