# Generated by Django 4.2.7 on 2024-01-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_localização_produtos_localizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='google_id',
            field=models.CharField(blank=True, editable=False, null=True),
        ),
    ]
